### ISSUE TITLE
 Error converting string to JSON object when using Spanish options (?)

### ISSUE THREAD

**Issue by fermaf** [run-llama/llama-lab#13]
# Error converting string to JSON object when using Spanish options

## Problem description

I'm using the following Spanish options for the script:

- **-it**: "Crea los pasos para ingresar"
- **-o**: "Subsidio DS49"

To debug the issue, I added these print lines before `initial_task_list = json.loads(initial_task_list_str)`:

```python
print("initial_task_list_str:", initial_task_list_str)
print("initial_task_list_str tipo:", type(initial_task_list_str))
print("initial_task_list_str longitud:", len(initial_task_list_str))
```
The output was:
```initial_task_list_str: 
[1. Revisar los requisitos para postular al subsidio del DS49,
2. Obtener los documentos necesarios para postular,
3. Completar la solicitud de subsidio del DS49,
4. Enviar la solicitud de subsidio del DS49,
5. Esperar la respuesta de la solicitud de subsidio del DS49.]
initial_task_list_str tipo: <class 'str'>
initial_task_list_str longitud: 275
```

It appears there is an issue with the JSON formatting in initial_task_list_str. The simple_execution_agent.execute_task function produces an output with incorrect formatting that causes the following error when attempting to convert it into a JSON object:
```
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 2 column 3 (char 3)```

**Comment by logan-markewich** [comment]
@fermaf just merged a fix for this, it should work a little better now!

The json was failing to parse because the task list didn't have quotes around the strings. Added a function to handle this.
